[package]
name = "templates"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true }
serde_yaml = { workspace = true }
thiserror = { workspace = true }
glob = { workspace = true }
tracing = { workspace = true }
protocol = { path = "../protocol" }

[dev-dependencies]
tempfile = { workspace = true }
