[package]
name = "workspace"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
protocol = { path = "../protocol" }
fileset = { path = "../fileset" }
sha2 = { workspace = true }
hex = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
walkdir = { workspace = true }
glob = { workspace = true }
templates = { path = "../templates" }
tokio = { workspace = true, features = ["sync"] }

[dev-dependencies]
tempfile = { workspace = true }
